//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GScript.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GScriptParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IGScriptListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GScriptParser.dialog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDialog([NotNull] GScriptParser.DialogContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GScriptParser.dialog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDialog([NotNull] GScriptParser.DialogContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GScriptParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] GScriptParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GScriptParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] GScriptParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GScriptParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommand([NotNull] GScriptParser.CommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GScriptParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommand([NotNull] GScriptParser.CommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GScriptParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterText([NotNull] GScriptParser.TextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GScriptParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitText([NotNull] GScriptParser.TextContext context);
}
